from __future__ import annotations

import json
from dataclasses import dataclass, asdict
from pathlib import Path


@dataclass
class QueueEntry:
    job_id: str           # UUID generated by us — links to SubmittedJob in memory
    image_filename: str
    uov_method: str
    positive_prompt: str
    seed: int
    status: str           # "queued" | "processing" | "done" | "failed" | "submitted (previous session)"
    submitted_at: str     # formatted timestamp string
    performance: str = "Speed"  # Fooocus Performance radio; default keeps old entries valid


class QueueManager:
    def __init__(self, queue_file: Path):
        self.queue_file = queue_file
        self.entries: list[QueueEntry] = self._load()

    def _load(self) -> list[QueueEntry]:
        if not self.queue_file.exists():
            return []
        try:
            data = json.loads(self.queue_file.read_text(encoding="utf-8"))
            entries = []
            for e in data:
                # Jobs in non-terminal states from a previous session can't be re-polled
                if e.get("status") in ("queued", "processing"):
                    e["status"] = "submitted (previous session)"
                entries.append(QueueEntry(**e))
            return entries
        except Exception:
            return []  # corrupt queue.json — start fresh

    def add(self, entry: QueueEntry) -> None:
        self.entries.append(entry)
        self._save()

    def update_status(self, job_id: str, status: str) -> None:
        for entry in self.entries:
            if entry.job_id == job_id:
                entry.status = status
                break
        self._save()

    def _save(self) -> None:
        self.queue_file.write_text(
            json.dumps([asdict(e) for e in self.entries], indent=2),
            encoding="utf-8",
        )

    def as_table_rows(self) -> list[list[str]]:
        """Returns rows for a Gradio DataFrame display, newest-first."""
        return [
            [e.image_filename, e.uov_method, e.performance, e.status, e.submitted_at]
            for e in reversed(self.entries)
        ]
