from __future__ import annotations

import json
from dataclasses import dataclass, asdict
from pathlib import Path


@dataclass
class QueueEntry:
    job_id: str           # UUID generated by us — links to SubmittedJob in memory
    image_filename: str
    uov_method: str
    positive_prompt: str
    seed: int
    status: str           # "queued" | "processing" | "done" | "failed" | "submitted (previous session)"
    submitted_at: str     # formatted timestamp string
    performance: str = "Speed"  # Fooocus Performance radio; default keeps old entries valid
    negative_prompt: str = ""   # stored so jobs can be re-queued on next launch
    image_path: str = ""        # absolute path to source image; empty for legacy entries


class QueueManager:
    def __init__(self, queue_file: Path):
        self.queue_file = queue_file
        self.entries: list[QueueEntry] = self._load()

    def _load(self) -> list[QueueEntry]:
        if not self.queue_file.exists():
            return []
        try:
            data = json.loads(self.queue_file.read_text(encoding="utf-8"))
            entries = []
            for e in data:
                if e.get("status") in ("queued", "processing"):
                    if e.get("image_path"):
                        # Keep as "queued" so startup can re-submit them
                        e["status"] = "queued"
                    else:
                        # Legacy entry — no stored path, can't re-submit
                        e["status"] = "submitted (previous session)"
                entries.append(QueueEntry(**e))
            return entries
        except Exception:
            return []  # corrupt queue.json — start fresh

    def add(self, entry: QueueEntry) -> None:
        self.entries.append(entry)
        self._save()

    def update_status(self, job_id: str, status: str) -> None:
        for entry in self.entries:
            if entry.job_id == job_id:
                entry.status = status
                break
        self._save()

    def update_job_id(self, old_id: str, new_id: str) -> None:
        """Replace job_id when an entry is re-submitted on startup."""
        for entry in self.entries:
            if entry.job_id == old_id:
                entry.job_id = new_id
                break
        self._save()

    def requeue_candidates(self) -> list[QueueEntry]:
        """Return entries that should be re-submitted on startup."""
        return [e for e in self.entries if e.status == "queued" and e.image_path]

    def _save(self) -> None:
        self.queue_file.write_text(
            json.dumps([asdict(e) for e in self.entries], indent=2),
            encoding="utf-8",
        )

    def as_table_rows(self) -> list[list[str]]:
        """Returns rows for a Gradio DataFrame display, newest-first."""
        return [
            [e.image_filename, e.uov_method, e.performance, e.status, e.submitted_at]
            for e in reversed(self.entries)
        ]
